FROM node:15

ENV NODE_ENV=production

WORKDIR /app

COPY .env .
COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY ./dist ./dist
COPY ./src/server ./src/server


EXPOSE 8080
CMD ["node", "./src/server/index.js"]